# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: pseudo-microbit
repo_url: https://github.com/MrYsLab/pseudo-microbit
copyright: > # should remain a link to the original theme
  Copyright &copy; 2024 Alan Yorinks &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  Last 
  Modified:
  October 17, 2024<br>


nav:
  - Introduction: index.md
  - Installing And Configuring PyCharm:
      - Installing PyCharm: pycharm_install.md
      - Creating A PyCharm Project: create_project.md
      - Installing pseudo-microbit: pm_install.md
      - Configuring PyCharm To Run External Tools:
        - Pycharm External Tools: external.md
        - Adding python-minimizer to PyCharm External Tools: minimizer.md
        - Adding uflash to PyCharm External Tools: uflash.md
        - Adding microfs to PyCharm External Tools: mfs.md
  - Working With Python Files and External User Tools:
    - Add A Directory To Your Project: add_directory.md
    - Add A File To Your Project: add_file.md
    - Minimize A File: file_min.md
    - Upload The File To The micro:bit: upload.md
    - Using the micro:bit Internal File System: using_mfs.md

  - Contact Info: contact.md
# theme: windmill

theme:
  name: 'material'
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.footer

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [ telemetrix_uno_r4/wifi/telemetrix_uno_r4_wifi,
                   telemetrix_uno_r4/wifi/telemetrix_uno_r4_wifi_aio,
                   telemetrix_uno_r4/minima/telemetrix_uno_r4_minima,
                   telemetrix_uno_r4/minima/telemetrix_uno_r4_minima_aio ]



